name:                brick-shgif
version:             1.1.0.2
github:              "Cj-bc/brick-shgif"
license:             BSD3
author:              "Cj.bc_sd a.k.a Cj-bc"
maintainer:          "cj.bc-sd@outlook.jp"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Cj-bc/brick-shgif#readme>

dependencies:
- base >= 4.7 && < 5
- yaml
- vty
- brick
- tart
- lens
- aeson
- vector
- text
- unordered-containers

library:
  source-dirs: src

executables:
  shgifView:
    main:                shgifView.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brick-shgif
  multipleShgifs:
    main:                multipleGifs.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - brick-shgif
  reversed:
    main:                reversed.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - brick-shgif
  compareReversed:
    main:                compareReversed.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - brick-shgif


tests:
  brick-shgif-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brick-shgif
